### PR TITLE
Remove flake and use UUIDs

### LINKED ISSUE #9: Replace Flake IDs with UUID (v4)
Since the way Flake IDs are used within kithara (naming of consumers) does not leverage their capabilities we should replace them with UUIDs. Additionally, this lets us remove a dependency.

### PR DESCRIPTION
**Pull request by lukaszkorecki**
Still work in progress, I need to do a bit more testing :-)

Fixes #9

### CODE REVIEW

**Comment by lukaszkorecki** [comment]
Tests pass locally just fine. UUIDs seem a bit long but I can't think for a better alternative right now

**Comment by xsc** [comment]
Looks good, thanks!

> UUIDs seem a bit long.

Maybe we could try one of the approaches outlined [here](http://connect2id.com/blog/how-to-generate-human-friendly-identifiers)? (Although, if we want to avoid a dependency, we'd have to implement Base32 encoding on our own.)

**Comment by lukaszkorecki** [comment]
Yeah, pulling Apache Commons just for the Base32 is a bit too much. From library users point of view there's not much of a difference to be honest so it might be ok just to use uuid4s

**Comment by xsc** [comment]
Released as

``` clojure
[kithara "0.1.7"]
```

[Release Notes](https://github.com/xsc/kithara/releases/tag/v0.1.7)

**Pull request merged**
